Mobile version navigation bar and headline section User Interface
kessio/Personal-Portfolio pull request #1
Opened 2022-06-30 15:32 UTC by kessio

This pull request contains a navigation bar and headline section UI design code parsed from Figma. The project contains HTML and CSS files used in the creation of the UI. HTML and CSS linters has been to flag programming errors, bugs, stylistic errors and suspicious constructs. This request also contains a descriptive README file and meaningful commit messages for every step taken when creating the portfolio.

2022-06-30 16:43 UTC, 1GORDON requested changes
##
## Hi @kessio.

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- Good commit messages  ✔️ 
- Professional Pull request ✔️
- Professional Readme ✔️
- Linters are passing ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 16:43 UTC, 1GORDON commented on index.html
> +            </nav>
Nice job @kessio. 👏

- [ ] [Optional] You may also make the logo and hamburger clickable links. You can surround each of these with `<a>` tags.

2022-06-30 16:43 UTC, 1GORDON commented on style.css
> +}
Great work @kessio. 👏

- [ ] Please try to fix the background image. It is repeating hence making your design very different from the one provided in the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md).
- Your design
![back-ground](https://user-images.githubusercontent.com/63917725/176730236-b04e32d3-b65e-4162-9efb-f2adeb51f704.PNG)

2022-07-01 03:13 UTC, Ismailco approved these changes
### Hi @kessio,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 03:13 UTC, Ismailco commented on index.html
> +         </div>
- [ ] [OPTIONAL] The icons should be wrapped in an `ul` tag, and each icon should be a `li`, then the icon is a link sung `a` tag, kindly implement this so your project is completed

2022-07-01 03:13 UTC, Ismailco commented on style.css
> +.container-homepage {
- [ ] [OPTIONAL] Make sure to use flex to align elements in this section

2022-07-01 04:32 UTC, merged