Contact Form Mobile version Template 1 (Pair programming)
kessio/Personal-Portfolio pull request #3
Opened 2022-07-05 13:03 UTC by kessio

This pull request contains a created contact form parsed from Figma Template 1 UI. The contact form was done in collaboration with two other authors who have been listed on the README file of this pull. The objective of this project is to work on linting errors, pair programming, form creation, form validation, and parsing UI from Figma.

2022-07-05 13:46 UTC, blessedjasonmwanza requested changes
# 👀  Status: Changes Required ♻️ 
> ### Hi @kessio && @mj-e-boc  && @PraisesPJMT ,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @blessedjasonmwanza in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-05 13:46 UTC, blessedjasonmwanza commented on style.css
> +.contact-section {
- [ ] The contact section should be centered and cover the entire width of a mobile device as per [design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122). Kindly consider centering it as you did for the projects section. Here is a UI difference reference to help you with this 🤓 
### Your current UI
![image](https://user-images.githubusercontent.com/35315311/177338682-a682ff58-296e-4afa-90f8-92e70574dc1d.png)
### Expected output

![image](https://user-images.githubusercontent.com/35315311/177338224-87368efd-e041-44b9-b856-af801be23848.png)

Use chrome dev tools to inspect and simulate how the project can look on different mobile devices. Checkout this [Article](https://www.browserstack.com/guide/view-mobile-version-of-website-on-chrome) for your reference.

2022-07-05 13:46 UTC, blessedjasonmwanza commented on index.html
> +                </div>
- [ ] The UI looks good 👍🏽 . However, for structural-semantic guidelines and in order for any `form`  to be submitted to the set action URL, It is required to use either a `button` with type `submit` or an `input` field with type `submit`. Here is a nice [article](https://www.w3schools.com/html/html_forms.asp#:~:text=The%20Submit%20Button,in%20the%20form's%20action%20attribute.) to help you with this part.

2022-07-05 13:46 UTC, blessedjasonmwanza commented on style.css
> +.contact-section {
- [ ] Kudos 👏🏽 for using `display: flex` in other parts of the project. Kindly note that you're also required to use flex here and throughout your project.

2022-07-05 22:22 UTC, blessedjasonmwanza commented on style.css
> +.contact-section {
Hi @kessio, The Figma width is portrayed on a 375 simulated device. You can utilize the power of CSS media queries and percentages to fill up an entire screen when the user is on smaller screens. Hopefully, this helps.

2022-07-06 05:15 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi Team 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great work on making the changes requested by the previous reviewer ✅
- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-06 05:15 UTC, Bondok6 commented on index.html
> +                    </div>
- [OPTIONAL] According to the requirements, You should Implement the button interactions (enable, hover, etc.). Kindly, add the button interactions based on your Figma Design 👌.

![1](https://user-images.githubusercontent.com/45231276/176833382-1d1d826d-6c66-47ac-bec8-36427809918f.PNG)

![image](https://user-images.githubusercontent.com/45231276/177019437-d4c20bc0-7e61-4d62-ac96-2b0d099054c1.png)

2022-07-06 07:58 UTC, merged